### ISSUE TITLE
Suggestion: Provide status codes to generate responses for

### ISSUE THREAD

**Issue by RyanMan56** [zoubingwu/msw-auto-mock#20]
I ran into an edge-case where I need to only generate responses for a given collection of status codes (e.g. 200,201). It would be nice if there was a flag that allowed us to pass in a csv of status codes and only generates responses that fulfill those conditions

**Comment by RyanMan56** [comment]
I have created a PR for this: [https://github.com/zoubingwu/msw-auto-mock/pull/21](https://github.com/zoubingwu/msw-auto-mock/pull/21)

**Comment by zoubingwu** [comment]
Thanks, this is released in v0.12.0
