### ISSUE TITLE
Get static data

### ISSUE THREAD

**Issue by ArthurGoupil** [zoubingwu/msw-auto-mock#32]
Hello !

Thanks for this beautiful lib!

I've started using it for our mocks generation but I'm facing an issue. We're using our mocks to run some visual regression tests, so with Faker it changes each times.

Is there a way to avoid this?
I guess I should propose a PR for an new option?

Thanks in advance,
Arthur

**Comment by zoubingwu** [comment]
for now, if your swagger have example data, this tool will use that instead of using faker, https://swagger.io/docs/specification/adding-examples/

**Comment by Wekios** [comment]
Why is this closed? When I use -h command static is not listed and when I try adding the static flag the process fails. Can anybody verify this works?
