### ISSUE TITLE
Can't work with faker v7

### ISSUE THREAD

**Issue by homerchen19** [zoubingwu/msw-auto-mock#4]
faker removed default export from [v7.0.0](https://github.com/faker-js/faker/releases/tag/v7.0.0)
It's a breaking change, so the way of importing faker (https://github.com/zoubingwu/msw-auto-mock/blob/master/src/template.ts#L14) should be changed to `import { faker } from '@faker-js/faker';`. Otherwise it can't work with faker v7.

**Comment by zoubingwu** [comment]
@homerchen19 Thanks! fixed and published in 0.7.0
