### ISSUE TITLE
Publish to npmjs.com - Latest version on npmjs.com doesn't support msw@2

### ISSUE THREAD

**Issue by Nill-Aarstiderne** [zoubingwu/msw-auto-mock#42]
Any plans to publish the current code to `npmjs.com`? :)
The latest version on `npmjs.com` (`msw-auto-mock@0.15.0`) supports `msw@1` but not `msw@2`.

**Comment by leogallot** [comment]
Apparently an `msw-auto-mock@0.16.0` version compatible with `msw@2` has been published on https://www.npmjs.com/package/msw-auto-mock.
