### ISSUE TITLE
Why is @faker-js/faker peer dependency now pinned?

### ISSUE THREAD

**Issue by PodStuart** [zoubingwu/msw-auto-mock#62]
In trying to pull in the latest version of this library we are getting an NPM conflict because we have @faker-js/faker in our package.json with version 8.4.1. As msw-auto-mock now specifies @faker-js/faker 8.2.0 as a peer dependency we get an error doing an npm install. I found the commit where the change was made but no obvious indication as to why.

**Comment by zoubingwu** [comment]
sorry this is a mistake and it was fixed in v0.23.0
